//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa phòng ban thành công!.
        /// </summary>
        public static string DeleteDepartmentSuccess {
            get {
                return ResourceManager.GetString("DeleteDepartmentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhân viên thành công!.
        /// </summary>
        public static string DeleteEmployeeSuccess {
            get {
                return ResourceManager.GetString("DeleteEmployeeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ MISA!.
        /// </summary>
        public static string ExceptionError {
            get {
                return ResourceManager.GetString("ExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa đổi thông tin nhân viên thành công!.
        /// </summary>
        public static string UpdateEmployeeSuccess {
            get {
                return ResourceManager.GetString("UpdateEmployeeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban bị trùng, vui lòng kiểm tra lại!.
        /// </summary>
        public static string ValidationError_DepartmentCodeDuplicated {
            get {
                return ResourceManager.GetString("ValidationError_DepartmentCodeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id phòng ban không tồn tại, vui lòng kiểm tra lại!.
        /// </summary>
        public static string ValidationError_DepartmentIdInexistent {
            get {
                return ResourceManager.GetString("ValidationError_DepartmentIdInexistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id phòng ban sai định dạng, vui lòng kiểm tra lại!.
        /// </summary>
        public static string ValidationError_DepartmentIdInvalid {
            get {
                return ResourceManager.GetString("ValidationError_DepartmentIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sai định dạng, vui lòng kiểm tra lại!.
        /// </summary>
        public static string ValidationError_EmailInvalid {
            get {
                return ResourceManager.GetString("ValidationError_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên bị trùng, vui lòng kiểm tra lại!.
        /// </summary>
        public static string ValidationError_EmployeeCodeDuplicated {
            get {
                return ResourceManager.GetString("ValidationError_EmployeeCodeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống, vui lòng kiểm tra lại!.
        /// </summary>
        public static string ValidationError_EmployeeCodeEmpty {
            get {
                return ResourceManager.GetString("ValidationError_EmployeeCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id nhân viên không tồn tại, vui lòng kiểm tra lại!.
        /// </summary>
        public static string ValidationError_EmployeeIdInexistent {
            get {
                return ResourceManager.GetString("ValidationError_EmployeeIdInexistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id nhân viên sai định dạng, vui lòng kiểm tra lại!.
        /// </summary>
        public static string ValidationError_EmployeeIdInvalid {
            get {
                return ResourceManager.GetString("ValidationError_EmployeeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMTND/CCCD không được phép để trống, vui lòng kiểm tra lại!.
        /// </summary>
        public static string ValidationError_IdentityNumberEmpty {
            get {
                return ResourceManager.GetString("ValidationError_IdentityNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại sai định dạng, vui lòng kiểm tra lại!.
        /// </summary>
        public static string ValidationError_PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("ValidationError_PhoneNumberInvalid", resourceCulture);
            }
        }
    }
}
